# EYEWITNESS DEMO RASA CORE - DEVELOPMENT DOCKERFILE

FROM rasa/rasa_nlu:0.11.3-spacy
MAINTAINER Atchai <enquiries@atchai.com>

ENV AWS_ACCESS_KEY_ID=AKIAJYIWY5U4SJCIEUMA
ENV AWS_SECRET_ACCESS_KEY=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

# Copy in our custom config.
COPY ./app/config/config.development.json /app/config.json
COPY ./app/trainingData.json /app/data/trainingData.json

# Training.
RUN python -m rasa_nlu.train -c /app/config.json --fixed_model_name trainingData
